version: '3.8'

name: nutri_track-backend

services:
  postgres:
    image: postgres:16-alpine
    container_name: nutri_track-backend-postgres
    environment:
      POSTGRES_DB: nutri_track
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: nutri_track-backend-redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/var/lib/redis/data

volumes:
  postgres_volume:
  redis_volume: